# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/forms/auth_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthForm(object):
    def setupUi(self, AuthForm):
        AuthForm.setObjectName("AuthForm")
        AuthForm.resize(389, 357)
        AuthForm.setMinimumSize(QtCore.QSize(389, 357))
        AuthForm.setMaximumSize(QtCore.QSize(389, 357))
        self.signInBtn = QtWidgets.QPushButton(AuthForm)
        self.signInBtn.setGeometry(QtCore.QRect(140, 250, 111, 31))
        self.signInBtn.setObjectName("signInBtn")
        self.signUpBtn = QtWidgets.QPushButton(AuthForm)
        self.signUpBtn.setGeometry(QtCore.QRect(130, 300, 131, 31))
        self.signUpBtn.setObjectName("signUpBtn")
        self.loginEdit = QtWidgets.QLineEdit(AuthForm)
        self.loginEdit.setGeometry(QtCore.QRect(100, 140, 231, 21))
        self.loginEdit.setObjectName("loginEdit")
        self.label = QtWidgets.QLabel(AuthForm)
        self.label.setGeometry(QtCore.QRect(40, 140, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AuthForm)
        self.label_2.setGeometry(QtCore.QRect(40, 180, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AuthForm)
        self.label_3.setGeometry(QtCore.QRect(70, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(True)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AuthForm)
        self.label_4.setGeometry(QtCore.QRect(60, 70, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.passwordEdit = QtWidgets.QLineEdit(AuthForm)
        self.passwordEdit.setGeometry(QtCore.QRect(100, 180, 231, 21))
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")

        self.retranslateUi(AuthForm)
        QtCore.QMetaObject.connectSlotsByName(AuthForm)

    def retranslateUi(self, AuthForm):
        _translate = QtCore.QCoreApplication.translate
        AuthForm.setWindowTitle(_translate("AuthForm", "Авторизация"))
        self.signInBtn.setText(_translate("AuthForm", "Войти"))
        self.signUpBtn.setText(_translate("AuthForm", "Я новенький!"))
        self.label.setText(_translate("AuthForm", "Логин:"))
        self.label_2.setText(_translate("AuthForm", "Пароль:"))
        self.label_3.setText(_translate("AuthForm", "Приложение библиотеки"))
        self.label_4.setText(_translate("AuthForm", "Yuh\' re welcome, buddy!"))
