# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/forms/book_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BookManager(object):
    def setupUi(self, BookManager):
        BookManager.setObjectName("BookManager")
        BookManager.resize(376, 500)
        BookManager.setMinimumSize(QtCore.QSize(376, 500))
        BookManager.setMaximumSize(QtCore.QSize(376, 500))
        self.label = QtWidgets.QLabel(BookManager)
        self.label.setGeometry(QtCore.QRect(30, 50, 51, 16))
        self.label.setObjectName("label")
        self.addBtn = QtWidgets.QPushButton(BookManager)
        self.addBtn.setGeometry(QtCore.QRect(80, 440, 81, 31))
        self.addBtn.setObjectName("addBtn")
        self.bookTitle = QtWidgets.QLineEdit(BookManager)
        self.bookTitle.setGeometry(QtCore.QRect(90, 50, 231, 20))
        self.bookTitle.setObjectName("bookTitle")
        self.bookGenres = QtWidgets.QLineEdit(BookManager)
        self.bookGenres.setGeometry(QtCore.QRect(90, 90, 231, 20))
        self.bookGenres.setObjectName("bookGenres")
        self.label_2 = QtWidgets.QLabel(BookManager)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(BookManager)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 51, 16))
        self.label_3.setObjectName("label_3")
        self.bookAuthor = QtWidgets.QLineEdit(BookManager)
        self.bookAuthor.setGeometry(QtCore.QRect(90, 130, 231, 20))
        self.bookAuthor.setObjectName("bookAuthor")
        self.cancelBtn = QtWidgets.QPushButton(BookManager)
        self.cancelBtn.setGeometry(QtCore.QRect(220, 440, 81, 31))
        self.cancelBtn.setObjectName("cancelBtn")
        self.bookDescription = QtWidgets.QTextEdit(BookManager)
        self.bookDescription.setGeometry(QtCore.QRect(30, 200, 291, 191))
        self.bookDescription.setObjectName("bookDescription")
        self.label_4 = QtWidgets.QLabel(BookManager)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 61, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(BookManager)
        QtCore.QMetaObject.connectSlotsByName(BookManager)

    def retranslateUi(self, BookManager):
        _translate = QtCore.QCoreApplication.translate
        BookManager.setWindowTitle(_translate("BookManager", "Book manager"))
        self.label.setText(_translate("BookManager", "Название:"))
        self.addBtn.setText(_translate("BookManager", "Добавить"))
        self.label_2.setText(_translate("BookManager", "Жанры:"))
        self.label_3.setText(_translate("BookManager", "Автор:"))
        self.cancelBtn.setText(_translate("BookManager", "Отмена"))
        self.bookDescription.setHtml(_translate("BookManager", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("BookManager", "Описание:"))
